
tool_and_translate_matching = {
    'Auto': {'language_tool':'auto', 'deep_translator': 'auto'},
    'Arabic (Generic)': {'language_tool':'ar', 'deep_translator': 'ar'},
    'Belarusian (Belarus)': {'language_tool':'be-BY', 'deep_translator': 'be'},
    'Belarusian (Generic)': {'language_tool':'be', 'deep_translator': 'be'},
    'Brazilian French': {'language_tool':'br-FR', 'deep_translator': 'br'},
    'Brazilian Portuguese (Generic)': {'language_tool':'br', 'deep_translator': 'br'},
    'Catalan (Balearic)': {'language_tool':'ca-ES-balear', 'deep_translator': 'ca'},
    'Catalan (Generic)': {'language_tool':'ca', 'deep_translator': 'ca'},
    'Catalan (Spain)': {'language_tool':'ca-ES', 'deep_translator': 'ca'},
    'Catalan (Valencia)': {'language_tool':'ca-ES-valencia', 'deep_translator': 'ca'},
    'Chinese (Traditional)': {'language_tool':'zh', 'deep_translator': 'zh-TW'},
    'Chinese (Simplified)': {'language_tool':'zh-CN', 'deep_translator': 'zh-CN'},
    'Danish (Denmark)': {'language_tool':'da-DK', 'deep_translator': 'da'},
    'Danish (Generic)': {'language_tool':'da', 'deep_translator': 'da'},
    'Dutch (Belgium)': {'language_tool':'nl-BE', 'deep_translator': 'nl'},
    'Dutch (Generic)': {'language_tool':'nl', 'deep_translator': 'nl'},
    'Dutch (Netherlands)': {'language_tool':'nl-NL', 'deep_translator': 'nl'},
    'English (Australia)': {'language_tool':'en-AU', 'deep_translator': 'en'},
    'English (Canada)': {'language_tool':'en-CA', 'deep_translator': 'en'},
    'English (Generic)': {'language_tool':'en', 'deep_translator': 'en'},
    'English (New Zealand)': {'language_tool':'en-NZ', 'deep_translator': 'en'},
    'English (South Africa)': {'language_tool':'en-ZA', 'deep_translator': 'en'},
    'English (United Kingdom)': {'language_tool':'en-GB', 'deep_translator': 'en'},
    'English (United States)': {'language_tool':'en-US', 'deep_translator': 'en'},
    'Esperanto (Generic)': {'language_tool':'eo', 'deep_translator': 'eo'},
    'Filipino (Generic)': {'language_tool':'tl', 'deep_translator': 'tl'},
    'Filipino (Philippines)': {'language_tool':'tl-PH', 'deep_translator': 'tl'},
    'French (Belgium)': {'language_tool':'fr-BE', 'deep_translator': 'fr'},
    'French (Canada)': {'language_tool':'fr-CA', 'deep_translator': 'fr'},
    'French (France)': {'language_tool':'fr-FR', 'deep_translator': 'fr'},
    'French (Generic)': {'language_tool':'fr', 'deep_translator': 'fr'},
    'French (Switzerland)': {'language_tool':'fr-CH', 'deep_translator': 'fr'},
    'Galician (Generic)': {'language_tool':'gl', 'deep_translator': 'gl'},
    'Galician (Spain)': {'language_tool':'gl-ES', 'deep_translator': 'gl'},
    'German (Austria)': {'language_tool':'de-AT', 'deep_translator': 'de'},
    'German (Generic)': {'language_tool':'de', 'deep_translator': 'de'},
    'German (Germany)': {'language_tool':'de-DE', 'deep_translator': 'de'},
    'German (Luxembourg)': {'language_tool':'de-LU', 'deep_translator': 'de'},
    'German (Simple Language)': {'language_tool':'de-DE-x-simple-language', 'deep_translator': 'de'},
    'German (Switzerland)': {'language_tool':'de-CH', 'deep_translator': 'de'},
    'Irish (Generic)': {'language_tool':'ga', 'deep_translator': 'ga'},
    'Irish (Ireland)': {'language_tool':'ga-IE', 'deep_translator': 'ga'},
    'Italian (Generic)': {'language_tool':'it', 'deep_translator': 'it'},
    'Italian (Italy)': {'language_tool':'it-IT', 'deep_translator': 'it'},
    'Japanese (Generic)': {'language_tool':'ja', 'deep_translator': 'ja'},
    'Japanese (Japan)': {'language_tool':'ja-JP', 'deep_translator': 'ja'},
    'Norwegian (Generic)': {'language_tool':'no', 'deep_translator': 'no'},
    'Norwegian Bokmål (Generic)': {'language_tool':'nb', 'deep_translator': 'no'},
    'Persian (Generic)': {'language_tool':'fa', 'deep_translator': 'fa'},
    'Persian (Iran)': {'language_tool':'fa-IR', 'deep_translator': 'fa'},
    'Polish (Generic)': {'language_tool':'pl', 'deep_translator': 'pl'},
    'Polish (Poland)': {'language_tool':'pl-PL', 'deep_translator': 'pl'},
    'Portuguese (Angola)': {'language_tool':'pt-AO', 'deep_translator': 'pt'},
    'Portuguese (Brazil)': {'language_tool':'pt-BR', 'deep_translator': 'pt'},
    'Portuguese (Generic)': {'language_tool':'pt', 'deep_translator': 'pt'},
    'Portuguese (Mozambique)': {'language_tool':'pt-MZ', 'deep_translator': 'pt'},
    'Portuguese (Portugal)': {'language_tool':'pt-PT', 'deep_translator': 'pt'},
    'Romanian (Generic)': {'language_tool':'ro', 'deep_translator': 'ro'},
    'Romanian (Romania)': {'language_tool':'ro-RO', 'deep_translator': 'ro'},
    'Russian (Generic)': {'language_tool':'ru', 'deep_translator': 'ru'},
    'Russian (Russia)': {'language_tool':'ru-RU', 'deep_translator': 'ru'},
    'Slovak (Generic)': {'language_tool':'sk', 'deep_translator': 'sk'},
    'Slovak (Slovakia)': {'language_tool':'sk-SK', 'deep_translator': 'sk'},
    'Slovenian (Generic)': {'language_tool':'sl', 'deep_translator': 'sl'},
    'Slovenian (Slovenia)': {'language_tool':'sl-SI', 'deep_translator': 'sl'},
    'Spanish (Argentina)': {'language_tool':'es-AR', 'deep_translator': 'es'},
    'Spanish (Generic)': {'language_tool':'es', 'deep_translator': 'es'},
    'Spanish (Spain)': {'language_tool':'es-ES', 'deep_translator': 'es'},
    'Swedish (Generic)': {'language_tool':'sv', 'deep_translator': 'sv'},
    'Swedish (Sweden)': {'language_tool':'sv-SE', 'deep_translator': 'sv'},
    'Turkish': {'language_tool':None, 'deep_translator': 'tr'},
    'Ukrainian (Generic)': {'language_tool':'uk', 'deep_translator': 'uk'},
    'Ukrainian (Ukraine)': {'language_tool':'uk-UA', 'deep_translator': 'uk'},
}

tesseract_lang = {}

#tool_and_translate_matching['Slovenian (Generic)']['language_tool']
#tool_and_translate_matching['Slovenian (Generic)']['deep_translator']















'''languages_googletranslate_code= {
    'afrikaans': 'af', 
    'albanian': 'sq', 
    'amharic': 'am', 
    'arabic': 'ar', 
    'armenian': 'hy', 
    'assamese': 'as', 
    'aymara': 'ay', 
    'azerbaijani': 'az', 
    'bambara': 'bm', 
    'basque': 'eu', 
    'belarusian': 'be', 
    'bengali': 'bn', 
    'bhojpuri': 'bho', 
    'bosnian': 'bs', 
    'bulgarian': 'bg', 
    'catalan': 'ca', 
    'cebuano': 'ceb', 
    'chichewa': 'ny', 
    'chinese (simplified)': 'zh-CN', 
    'chinese (traditional)': 'zh-TW', 
    'corsican': 'co', 
    'croatian': 'hr', 
    'czech': 'cs', 
    'danish': 'da', 
    'dhivehi': 'dv', 
    'dogri': 'doi', 
    'dutch': 'nl', 
    'english': 'en', 
    'esperanto': 'eo', 
    'estonian': 'et', 
    'ewe': 'ee', 
    'filipino': 'tl', 
    'finnish': 'fi', 
    'french': 'fr', 
    'frisian': 'fy', 
    'galician': 'gl', 
    'georgian': 'ka', 
    'german': 'de', 
    'greek': 'el', 
    'guarani': 'gn', 
    'gujarati': 'gu', 
    'haitian creole': 'ht', 
    'hausa': 'ha', 
    'hawaiian': 'haw', 
    'hebrew': 'iw', 
    'hindi': 'hi', 
    'hmong': 'hmn', 
    'hungarian': 'hu', 
    'icelandic': 'is', 
    'igbo': 'ig', 
    'ilocano': 'ilo', 
    'indonesian': 'id', 
    'irish': 'ga', 
    'italian': 'it', 
    'japanese': 'ja', 
    'javanese': 'jw', 
    'kannada': 'kn', 
    'kazakh': 'kk', 
    'khmer': 'km', 
    'kinyarwanda': 'rw', 
    'konkani': 'gom', 
    'korean': 'ko', 
    'krio': 'kri', 
    'kurdish (kurmanji)': 'ku', 
    'kurdish (sorani)': 'ckb', 
    'kyrgyz': 'ky', 
    'lao': 'lo', 
    'latin': 'la', 
    'latvian': 'lv', 
    'lingala': 'ln', 
    'lithuanian': 'lt', 
    'luganda': 'lg', 
    'luxembourgish': 'lb', 
    'macedonian': 'mk', 
    'maithili': 'mai', 
    'malagasy': 'mg', 
    'malay': 'ms', 
    'malayalam': 'ml', 
    'maltese': 'mt', 
    'maori': 'mi', 
    'marathi': 'mr', 
    'meiteilon (manipuri)': 'mni-Mtei', 
    'mizo': 'lus', 
    'mongolian': 'mn', 
    'myanmar': 'my', 
    'nepali': 'ne', 
    'norwegian': 'no', 
    'odia (oriya)': 'or', 
    'oromo': 'om', 
    'pashto': 'ps', 
    'persian': 'fa', 
    'polish': 'pl', 
    'portuguese': 'pt', 
    'punjabi': 'pa', 
    'quechua': 'qu', 
    'romanian': 'ro', 
    'russian': 'ru', 
    'samoan': 'sm', 
    'sanskrit': 'sa', 
    'scots gaelic': 'gd', 
    'sepedi': 'nso', 
    'serbian': 'sr', 
    'sesotho': 'st', 
    'shona': 'sn', 
    'sindhi': 'sd', 
    'sinhala': 'si', 
    'slovak': 'sk', 
    'slovenian': 'sl', 
    'somali': 'so', 
    'spanish': 'es', 
    'sundanese': 'su', 
    'swahili': 'sw', 
    'swedish': 'sv', 
    'tajik': 'tg', 
    'tamil': 'ta', 
    'tatar': 'tt', 
    'telugu': 'te', 
    'thai': 'th', 
    'tigrinya': 'ti', 
    'tsonga': 'ts', 
    'turkish': 'tr', 
    'turkmen': 'tk', 
    'twi': 'ak', 
    'ukrainian': 'uk', 
    'urdu': 'ur', 
    'uyghur': 'ug', 
    'uzbek': 'uz', 
    'vietnamese': 'vi', 
    'welsh': 'cy', 
    'xhosa': 'xh', 
    'yiddish': 'yi', 
    'yoruba': 'yo', 
    'zulu': 'zu'
}




language_tool_paython_support_lang = {
    'nl', 
    'br-FR', 
    'fr-FR', 
    'en-GB', 
    'ja-JP', 
    'ru', 
    'pl', 
    'de-DE-x-simple-language', 
    'en-US', 
    'sl', 
    'km', 
    'zh-CN', 
    'be-BY', 
    'fr', 
    'ro-RO', 
    'pt-PT', 
    'da', 
    'nl-BE', 
    'ca-ES-balear', 
    'ca-ES-valencia', 
    'fr-CA', 
    'gl-ES', 
    'zh', 
    'ta-IN', 
    'ca-ES', 
    'it-IT', 
    'nl-NL', 
    'fr-BE', 
    'sk-SK', 
    'ca', 
    'pt', 
    'es-ES', 
    'tl', 
    'en-ZA', 
    'de-CH', 
    'ga', 
    'ru-RU', 
    'ja', 
    'ar', 
    'pl-PL', 
    'ta', 
    'de-DE', 
    'sv-SE', 
    'de', 
    'da-DK', 
    'fr-CH', 
    'crh-UA', 
    'sk', 
    'crh', 
    'es', 
    'de-LU', 
    'en-AU', 
    'ga-IE', 
    'gl', 
    'pt-AO', 
    'ast', 
    'sl-SI', 
    'tl-PH', 
    'pt-BR', 
    'fa', 
    'en', 
    'es-AR', 
    'br', 
    'en-CA', 
    'ast-ES', 
    'km-KH', 
    'pt-MZ', 
    'eo', 
    'nb', 
    'el', 
    'auto', 
    'uk', 
    'el-GR', 
    'it', 
    'de-AT', 
    'no', 
    'uk-UA', 
    'en-NZ', 
    'sv', 
    'de-DE-x-simple-language-DE', 
    'ro', 
    'be', 
    'fa-IR'
}


language_tool_meaning = {
    'Arabic (Generic)': 'ar',
    'Asturian (Generic)': 'ast',
    'Asturian (Spain)': 'ast-ES',
    'Automatic language detection': 'auto',
    'Belarusian (Belarus)': 'be-BY',
    'Belarusian (Generic)': 'be',
    'Brazilian French': 'br-FR',
    'Brazilian Portuguese (Generic)': 'br',
    'Catalan (Balearic)': 'ca-ES-balear',
    'Catalan (Generic)': 'ca',
    'Catalan (Spain)': 'ca-ES',
    'Catalan (Valencia)': 'ca-ES-valencia',
    'Chinese (Generic)': 'zh',
    'Chinese (Simplified)': 'zh-CN',
    'Crimean Tatar (Generic)': 'crh',
    'Crimean Tatar (Ukraine)': 'crh-UA',
    'Danish (Denmark)': 'da-DK',
    'Danish (Generic)': 'da',
    'Dutch (Belgium)': 'nl-BE',
    'Dutch (Generic)': 'nl',
    'Dutch (Netherlands)': 'nl-NL',
    'English (Australia)': 'en-AU',
    'English (Canada)': 'en-CA',
    'English (Generic)': 'en',
    'English (New Zealand)': 'en-NZ',
    'English (South Africa)': 'en-ZA',
    'English (United Kingdom)': 'en-GB',
    'English (United States)': 'en-US',
    'Esperanto (Generic)': 'eo',
    'Filipino (Generic)': 'tl',
    'Filipino (Philippines)': 'tl-PH',
    'French (Belgium)': 'fr-BE',
    'French (Canada)': 'fr-CA',
    'French (France)': 'fr-FR',
    'French (Generic)': 'fr',
    'French (Switzerland)': 'fr-CH',
    'Galician (Generic)': 'gl',
    'Galician (Spain)': 'gl-ES',
    'German (Austria)': 'de-AT',
    'German (Generic)': 'de',
    'German (Germany)': 'de-DE',
    'German (Luxembourg)': 'de-LU',
    'German (Simple Language - DE Variant)': 'de-DE-x-simple-language-DE',
    'German (Simple Language)': 'de-DE-x-simple-language',
    'German (Switzerland)': 'de-CH',
    'Irish (Generic)': 'ga',
    'Irish (Ireland)': 'ga-IE',
    'Italian (Generic)': 'it',
    'Italian (Italy)': 'it-IT',
    'Japanese (Generic)': 'ja',
    'Japanese (Japan)': 'ja-JP',
    'Norwegian (Generic)': 'no',
    'Norwegian Bokmål (Generic)': 'nb',
    'Persian (Generic)': 'fa',
    'Persian (Iran)': 'fa-IR',
    'Polish (Generic)': 'pl',
    'Polish (Poland)': 'pl-PL',
    'Portuguese (Angola)': 'pt-AO',
    'Portuguese (Brazil)': 'pt-BR',
    'Portuguese (Generic)': 'pt',
    'Portuguese (Mozambique)': 'pt-MZ',
    'Portuguese (Portugal)': 'pt-PT',
    'Romanian (Generic)': 'ro',
    'Romanian (Romania)': 'ro-RO',
    'Russian (Generic)': 'ru',
    'Russian (Russia)': 'ru-RU',
    'Slovak (Generic)': 'sk',
    'Slovak (Slovakia)': 'sk-SK',
    'Slovenian (Generic)': 'sl',
    'Slovenian (Slovenia)': 'sl-SI',
    'Spanish (Argentina)': 'es-AR',
    'Spanish (Generic)': 'es',
    'Spanish (Spain)': 'es-ES',
    'Swedish (Generic)': 'sv',
    'Swedish (Sweden)': 'sv-SE',
    'Ukrainian (Generic)': 'uk',
    'Ukrainian (Ukraine)': 'uk-UA',
}'''
